import { Place } from './types';

export const places: Place[] = [
  {
    id: '1',
    title: 'Beautiful & luxurious apartment at great location',
    type: 'Apartment',
    price: 120,
    imageUrl: 'img/apartment-01.jpg',
    isPremium: true,
    isFavorite: false,
    rating: 4,
  },
  {
    id: '2',
    title: 'Wood and stone place',
    type: 'Room',
    price: 80,
    imageUrl: 'img/room.jpg',
    isPremium: false,
    isFavorite: true,
    rating: 4,
  },
  {
    id: '3',
    title: 'Canal View Prinsengracht',
    type: 'Apartment',
    price: 132,
    imageUrl: 'img/apartment-02.jpg',
    isPremium: false,
    isFavorite: false,
    rating: 4,
  },
  {
    id: '4',
    title: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
    price: 180,
    imageUrl: 'img/apartment-03.jpg',
    isPremium: true,
    isFavorite: false,
    rating: 4,
  },
  {
    id: '5',
    title: 'Wood and stone place',
    type: 'Room',
    price: 80,
    imageUrl: 'img/room.jpg',
    isPremium: false,
    isFavorite: true,
    rating: 4,
  },
];
